---
title: "STAT 417 Final Code Work"
author: "Nicholas Todd"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

### Initial data pull/clean
```{r}
#read the data from the fed website
library(readr)
url <- "https://fred.stlouisfed.org/graph/fredgraph.csv?id=UNRATENSA"
unrate_data <- read_csv(url)

#convert to time series
unrate_ts <- ts(unrate_data$UNRATENSA, start = c(1948, 1), frequency = 12)
#interpolate the NA values
library(forecast)
unrate_ts_interp <- na.interp(unrate_ts)
```

### ts analysis
```{r}
#full data set and smoothing
plot(unrate_ts_interp, ylab="Unemployment Rate (NSA)", xlab = "time", col = "black", main = "Monthly Unemployment Rate, USA, Not Seasonally Adjusted")
lines(lowess(unrate_ts_interp, f=0.01), lwd=2, col="red")

#stl analysis
unrate_stl <- stl(unrate_ts_interp, s.window = "periodic")
plot(unrate_stl)
season <- unrate_stl$time.series[,1]
trend <- unrate_stl$time.series[,2]
res <- unrate_stl$time.series[,3]

acf(res, main = "ACF(residuals) Unrate data")
```
We can see seasonality in the tiny spikes, probably should blow this graph up on the ppt.

ACF reveals time dependence of the residuals, so we need to model the residuals.

### Residual AR fit model
```{r}
#get the order of the AR fit
fit_ar <- ar.yw(res, order.max = NULL)
fit_ar
#plot the AR fit#################fix this
#fir_ar_coef <- coefficients(fit_ar$ar)
#plot(fit_ar_coef)

#look at the residuals for this new model
fit_ar <- ar.yw(res, order.max = NULL)
fit_resid <- ts(fit_ar$resid)
p<- fit_ar$order
acf(fit_resid[-c(1:p)], main = "ACF AR fit residuals") #remove the first p(order) observations, the rest are res
```

### Trend model
```{r}
plot(trend)

```

### Seasonal model

